[package]
name = "unique-id-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
OpenFaaSRPC = { path = "../OpenFaaSRPC" }
serde_json = "1.0.79"
rand = "0.8.5"
